# Generated by Django 2.0.8 on 2018-08-31 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets_management', '0002_auto_20180831_1602'),
        ('department', '0002_auto_20180831_1602'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='年度')),
                ('date_of_application', models.DateField(auto_now_add=True, verbose_name='申请日期')),
                ('application_status', models.CharField(max_length=20, verbose_name='申请状态')),
                ('assets', models.ManyToManyField(to='assets_management.Assets')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.Department')),
                ('operator', models.ManyToManyField(related_name='plan_operator', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
