# Generated by Django 2.0.8 on 2018-08-31 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plan_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='assets',
            field=models.ManyToManyField(to='assets_management.Assets', verbose_name='资产'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.Department', verbose_name='申报部门'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='operator',
            field=models.ManyToManyField(related_name='plan_operator', to=settings.AUTH_USER_MODEL, verbose_name='操作人'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_user', to=settings.AUTH_USER_MODEL, verbose_name='申报人'),
        ),
    ]
