# Generated by Django 2.0.8 on 2018-08-31 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan_management', '0002_auto_20180831_1603'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'permissions': (('can_see', '能看到计划管理模块'),), 'verbose_name_plural': '计划管理'},
        ),
    ]
