# Generated by Django 2.0.8 on 2018-09-03 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plan_management', '0003_auto_20180831_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': '申请状态',
            },
        ),
        migrations.AlterField(
            model_name='plan',
            name='application_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan_management.ApplicationStatus', verbose_name='申请状态'),
        ),
    ]
