# Generated by Django 2.0.8 on 2018-09-05 10:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan_management', '0004_auto_20180903_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='date_of_application',
            field=models.DateField(verbose_name='申请日期'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='operator',
            field=models.ManyToManyField(null=True, related_name='plan_operator', to=settings.AUTH_USER_MODEL, verbose_name='操作人'),
        ),
    ]
