# Generated by Django 2.0.8 on 2018-08-31 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assets_name', models.CharField(max_length=20, verbose_name='资产名称')),
                ('price', models.FloatField(verbose_name='价格')),
                ('order', models.IntegerField(verbose_name='次序')),
            ],
        ),
    ]
