# Generated by Django 2.0.8 on 2018-08-31 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assets',
            options={'verbose_name_plural': '资产管理'},
        ),
    ]
