# Generated by Django 2.0.8 on 2018-09-11 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departmentreview',
            options={'verbose_name_plural': '部门审核表'},
        ),
        migrations.AlterModelOptions(
            name='logisticsreview',
            options={'verbose_name_plural': '后勤审核表'},
        ),
        migrations.AlterField(
            model_name='departmentreview',
            name='review_content',
            field=models.CharField(max_length=50, verbose_name='审核内容'),
        ),
        migrations.AlterField(
            model_name='departmentreview',
            name='review_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='审核时间'),
        ),
        migrations.AlterField(
            model_name='departmentreview',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='审核人员'),
        ),
        migrations.AlterField(
            model_name='logisticsreview',
            name='review_content',
            field=models.CharField(max_length=50, verbose_name='审核内容'),
        ),
        migrations.AlterField(
            model_name='logisticsreview',
            name='review_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='审核时间'),
        ),
        migrations.AlterField(
            model_name='logisticsreview',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='审核人员'),
        ),
    ]
