# Generated by Django 2.0.8 on 2018-08-31 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name_plural': '部门管理'},
        ),
    ]
